- src/main/scala/info/mukel/telegram/bots/Commands.scala
- src/main/scala/info/mukel/telegram/bots/Polling.scala
- src/main/scala/info/mukel/telegram/bots/TelegramBot.scala
- src/main/scala/info/mukel/telegram/bots/api/TelegramBotApi.scala
- src/main/scala/info/mukel/telegram/bots/http/HttpClient.scala
- src/main/scala/info/mukel/telegram/bots/http/ScalajHttpClient.scala
All API methods now are async. Left sync http request alongside with async http request.
I can't determine how best to resolve the definition of
```scala
lazy val botName: String = getMe.username.get
```
so while left so
```scala
lazy val botName: String = Await.result(getMe.map(_.username.get), 5.seconds)
```
> made the API async

- src/main/scala/info/mukel/telegram/bots/AuthorizationManager.scala
- src/main/scala/info/mukel/telegram/bots/Commands.scala
The authorization manager takes care of the authorization when talking to a bot.
This way you could create a private bot that will only respond to specific channels.
The authorization can work either by whitelisting or blacklisting channels.
By default the policy is to accept all channels.
Waiting for a config file to add static channels to the list (currently this can only be done from the code)
> Authorization manager

- README.md
Apparently by default it looks for a 2.10 version. That makes me think that
`scalaVersion := "2.10.x"` won't work either. Anyway, feel free to reject it or whatever.
Closes #20
> This is rather a documentation fix

- src/main/resources/application.conf
application.conf creates conflicts when using as a library, it should be reference.conf if anything.
> Remove application.conf

- src/main/scala/info/mukel/telegrambot4s/api/Commands.scala
In group chats commands to bot look like command@my_bot. Bot doesn't actually need that @my_bot part, since it'll not get commands for the other bots and it's forbidden to use @ in command names.
> strip off bot's name from command

- .gitignore
- src/main/scala/info/mukel/telegrambot4s/api/Commands.scala
- src/main/scala/info/mukel/telegrambot4s/methods/EditMessageReplyMarkup.scala
It's a minor fix. I discovered this issue trying to edit non-inline reply markup 😅 
[Docs](https://core.telegram.org/bots/api#editmessagereplymarkup) also mention it.
I also added a `.gitignore`. I'm not sure whether you didn't have it on purpose or not..
> EditMessageReplyMarkup can edit only inline reply markup

- README.md
See https://jitpack.io/#mukel/telegrambot4s/v2.0.1:
- single `%` instead of usual `%%`
- the latest tag is `v2.0.1`
Why is it "deprecated" by the way?
> Fixed JitPack dependency reference

- core/src/main/scala/info/mukel/telegrambot4s/api/Extractors.scala
- core/src/main/scala/info/mukel/telegrambot4s/api/declarative/Commands.scala
- core/src/main/scala/info/mukel/telegrambot4s/api/declarative/package.scala
I'd like to be able to write such code:
```
onMessage { implicit msg =>
using(command) { cmd =>
...
}
}
```
Also, I refactored a bit Commands#onCommand method using new extractors.
> Create public command extractors, use them in Commands#onCommand

- examples/src/main/scala/LmgtfyBot.scala
There was an error in the Lmgtfy example, where _/pepe_ would trigger the _/lmgtfy2_ command, which should've been achieved by inserting _/btn_.
As stated in the help text, _/btn_ should be used for this command.
> Fixes wrong command in LmgtfyBot example

- core/src/main/scala/info/mukel/telegrambot4s/api/BotBase.scala
I'd like to use `StrictLogging`'s logger from https://github.com/typesafehub/scala-logging library this way:
`class MyBot extends BotBase with StrictLogging { ... }`
However, logger in `StrictLogging` is protected, so, it fails to compile without this patch.
Also, it just makes no sense to me to make logger public.
> Make BotBase#logger protected

- core/src/com/bot4s/telegram/api/RequestHandler.scala
- core/src/com/bot4s/telegram/marshalling/CirceEncoders.scala
- core/src/com/bot4s/telegram/methods/SendAnimation.scala
```
scala.MatchError: SendAnimation(Chat(****),FileId(***),None,None,None,None,None,None,None,None,None) (of class com.bot4s.telegram.methods.SendAnimation)
```
Also adding missing default `None` to `replyToMessageId    : Option[Int]`
> Add missing SendAnimation request handler

- core/src/com/bot4s/telegram/marshalling/CirceDecoders.scala
- core/src/com/bot4s/telegram/marshalling/CirceEncoders.scala
- core/src/com/bot4s/telegram/methods/PollType.scala
- core/src/com/bot4s/telegram/methods/SendPoll.scala
- core/src/com/bot4s/telegram/models/PhotoSize.scala
- examples/src/PollBot.scala
The SendPoll API can be used to send quizzes on telegram.
A missing additional field `fileUniqueId` was added on the `PhotoSize`
object.
Please refer to `PollBot.scala` for a simple usage of the quiz API.
Fixes #90
Fixes #89
> [api] Add support for Quizzes using SendPoll

- .gitignore
- core/src/com/bot4s/telegram/api/declarative/Messages.scala
- core/src/com/bot4s/telegram/marshalling/CirceEncoders.scala
- core/src/com/bot4s/telegram/methods/ParseMode.scala
- examples/src/MarkdownBot.scala
Telegram release a new version of the markdown mode.
This was documented https://core.telegram.org/bots/api#markdownv2-style
It allows nested style and is more powerful than the first version.
There are a few rules to respect in order to use the new markdown style:
```
-  Any character with code between 1 and 126 inclusively can be escaped anywhere with a preceding '\' character, in which case it is treated as an ordinary character and not a part of the markup.
-  Inside pre and code entities, all '`' and '\' characters must be escaped with a preceding '\' character.
-  Inside (...) part of inline link definition, all ')' and '\' must be escaped with a preceding '\' character.
-  In all other places characters '_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', …
```
> [api][markdown] Add MarkdownV2 format

- core/src/com/bot4s/telegram/api/declarative/Commands.scala
- core/test/src/com/bot4s/telegram/api/CommandsSuite.scala
- examples/src-cats/CommandsBot.scala
- examples/src-jvm/LmgtfyBot.scala
- examples/src-jvm/ProxyBot.scala
- examples/src-jvm/QrCodesBot.scala
- examples/src/AuthenticationBot.scala
- examples/src/CommandsBot.scala
- examples/src/PokerBot.scala
- examples/src/ProcessBot.scala
- examples/src/RandomBot.scala
Scala deprecated the support for Symbols (in 2.13) and they will we removed in next versions.
This introduces a breaking changes, without deprecation warning for the bot using Symbol as input.
Fixes #105
> [scala][api] Remove support for Symbols

- README.md
Snapshot are now automatically published from the latest commit on master.
This badge will give easy access to the snapshot repository on oss.sonatype.org
> [readme] Add nexus snapshot badge

- akka/src/com/bot4s/telegram/api/AkkaTelegramBot.scala
- akka/src/com/bot4s/telegram/api/GameManager.scala
- akka/src/com/bot4s/telegram/api/WebRoutes.scala
- akka/src/com/bot4s/telegram/clients/YetAnotherAkkaClient.scala
- akka/test/src/com/bot4s/telegram/marshalling/AkkaHttpMarshallingSuite.scala
Remove warnings when compiling the Akka library using 2.13.
All of those are related to the upgrade from 2.X  to 2.6 of Akka.
> [cleanup][akka] Remove warning in Akka implementation

- build.sc
- core/src/com/bot4s/telegram/cats/TelegramBot.scala
- core/src/com/bot4s/telegram/clients/FutureSttpClient.scala
- core/src/com/bot4s/telegram/clients/SttpClient.scala
- core/test/src/com/bot4s/telegram/clients/SttpClientSuite.scala
- examples/src-cats/CommandsBot.scala
- examples/src-cats/EchoBot.scala
- examples/src-cats/ExampleBot.scala
- examples/src-jvm/SttpBackends.scala
- examples/src-monix/EchoBot.scala
- examples/src-monix/ExampleBot.scala
- examples/src/CovfefeBot.scala
The project was using STTP1. Two majors versions were released and version 3 is now stable.
The migration was done to stay as close as possible from the implementation using STTP1.
A few major changes:
- Handling error is now done in the `responses` method instead of using `_.unsafeBody`
- The capabilities type has been changed from `Nothing` to `Any` as described in STTP's documentation
- Cats' `Async` was changed to `Concurrent`
- `asyncHttpClient` has to be manually created, we might need to close it as well, but in the scope of bot, this should not be an issue
I've successfully run the following bot after the migration:
- monix echo bot
- jvmcats commandsbot
- jvm randombot
Fixes #104
> [deps] Upgrade to STTP3

- README.md
- build.sc
- core/src/com/bot4s/telegram/clients/SttpClient.scala
The map of parameters was not correctly parsed in all cases and the string `MapView(<not computed>)` was sent to the server.
This only happened in Scala 2.13. 
This PR explicitly converts the MapView to a Map
> [fix][scala2.13] Convert map view to map in STTP send

- core/src/com/bot4s/telegram/api/Polling.scala
- core/src/com/bot4s/telegram/cats/Polling.scala
- core/src/com/bot4s/telegram/future/Polling.scala
- core/src/com/bot4s/telegram/marshalling/CirceDecoders.scala
- core/src/com/bot4s/telegram/marshalling/CirceEncoders.scala
- core/src/com/bot4s/telegram/methods/GetUpdates.scala
- core/src/com/bot4s/telegram/models/Update.scala
- core/test/src/com/bot4s/telegram/marshalling/MarshallingSuite.scala
The `ParsedUpdate` type was introduce in order to be able to represent parsing issues in the `GetUpdates` endpoint.
With the previous implementation, when a new or unknown type of message was received by the client, the parser would fail and cause the bot to stop parsing new messages.
The new implementation extracts the `update_id` message in case of parsing issue in order to acknowledge the message and receive the next ones. It also extracts and logs the decoding error from Circe in order to fix them in the next release of the library.
This PR also includes a fix to run some tests that were skipped so far as well as correctly serializing the `CallbackGame` case object.
See #143
> Wrap Update to include errors

- core/src/com/bot4s/telegram/api/BotBase.scala
- core/src/com/bot4s/telegram/api/RequestHandler.scala
- core/src/com/bot4s/telegram/api/declarative/JoinRequests.scala
- core/src/com/bot4s/telegram/marshalling/CirceDecoders.scala
- core/src/com/bot4s/telegram/marshalling/CirceEncoders.scala
- core/src/com/bot4s/telegram/methods/ApproveChatJoinRequest.scala
- core/src/com/bot4s/telegram/methods/ChatAction.scala
- core/src/com/bot4s/telegram/methods/CreateChatInviteLink.scala
- core/src/com/bot4s/telegram/methods/DeclineChatJoinRequest.scala
- core/src/com/bot4s/telegram/methods/EditChatInviteLink.scala
- core/src/com/bot4s/telegram/models/Chat.scala
- core/src/com/bot4s/telegram/models/ChatInviteLink.scala
- core/src/com/bot4s/telegram/models/ChatJoinRequest.scala
- core/src/com/bot4s/telegram/models/Update.scala
- examples/src/JoinRequestBot.scala
Bot API 5.4
-  Added the the parameter creates_join_request to the methods createChatInviteLink and editChatInviteLink for managing chat invite links that create join requests (read more about this on our blog).
-  Added the fields creates_join_request and pending_join_request_count to the class ChatInviteLink.
-  Added the field name to the class ChatInviteLink and the parameters name to the methods createChatInviteLink and editChatInviteLink for managing invite link names.
-   Added updates about new requests to join the chat, represented by the class ChatJoinRequest and the field chat_join_request in the Update class. The bot must be an administrator in the chat with the can_invite_users administrator right to receive these updates.
-   Added the methods approveChatJoinRequest and …
> Add Api 5.4 changes

- core/src/com/bot4s/telegram/api/declarative/Commands.scala
- core/src/com/bot4s/telegram/models/BotCommand.scala
- core/test/src/com/bot4s/telegram/api/CommandsSuite.scala
- examples/src/CommandsBot.scala
This will ensure that the command is in lowercase and that the description is not too long.
This is not perfect as one could still use the copy construct to bypass those limitation, but the goal is to reduce the frustration of developers using the library (see https://github.com/bot4s/telegram/issues/190). Furthermore, the API does not give us a lot of details for invalid input, and it's pretty hard to guess what is going wrong.
This also fix the support for unicode characters in command (which is supposed to work but is probably broken for quite some time now). We might want to remove/update those regex in a future release
> [api] Re-enable support for unicode commands

- core/src/com/bot4s/telegram/models/ReplyMarkup.scala
Hi there, just noticed that a couple of classes in `ReplyMarkup` were missing a `input_field_placeholder` field:
* https://core.telegram.org/bots/api#replykeyboardmarkup
* https://core.telegram.org/bots/api#forcereply
Added them following the same convention as the rest of the optional fields in those classes.
> Add input field placeholder to reply markup keyboard and force reply

- core/src/com/bot4s/telegram/api/RequestHandler.scala
- core/src/com/bot4s/telegram/marshalling/CirceDecoders.scala
- core/src/com/bot4s/telegram/marshalling/CirceEncoders.scala
- core/src/com/bot4s/telegram/methods/AnswerWebAppQuery.scala
- core/src/com/bot4s/telegram/methods/GetChatMenuButton.scala
- core/src/com/bot4s/telegram/methods/GetMyDefaultAdministratorRights.scala
- core/src/com/bot4s/telegram/methods/PromoteChatMember.scala
- core/src/com/bot4s/telegram/methods/SetChatMenuButton.scala
- core/src/com/bot4s/telegram/methods/SetMyDefaultAdministratorRights.scala
- core/src/com/bot4s/telegram/models/ChatAdministratorRights.scala
- core/src/com/bot4s/telegram/models/ChatMember.scala
- core/src/com/bot4s/telegram/models/MenuButton.scala
- core/src/com/bot4s/telegram/models/Message.scala
- core/src/com/bot4s/telegram/models/ReplyMarkup.scala
- core/src/com/bot4s/telegram/models/SentWebAppMessage.scala
- core/src/com/bot4s/telegram/models/VideoChatEnded.scala
- core/src/com/bot4s/telegram/models/VideoChatParticipantsInvited.scala
- core/src/com/bot4s/telegram/models/VideoChatScheduled.scala
- core/src/com/bot4s/telegram/models/VideoChatStarted.scala
- core/src/com/bot4s/telegram/models/WebAppData.scala
- core/src/com/bot4s/telegram/models/WebAppInfo.scala
- core/src/com/bot4s/telegram/models/WebhookInfo.scala
- core/test/src/com/bot4s/telegram/marshalling/MarshallingSuite.scala
- examples/src/JoinRequestBot.scala
https://core.telegram.org/bots/api#april-16-2022
> [api] Support v6.0

- core/src/com/bot4s/telegram/api/RequestHandler.scala
- core/src/com/bot4s/telegram/marshalling/CirceDecoders.scala
- core/src/com/bot4s/telegram/marshalling/CirceEncoders.scala
- core/src/com/bot4s/telegram/methods/CreateNewStickerSet.scala
- core/src/com/bot4s/telegram/methods/GetCustomEmojiStickers.scala
- core/src/com/bot4s/telegram/models/Chat.scala
- core/src/com/bot4s/telegram/models/MenuButton.scala
- core/src/com/bot4s/telegram/models/MessageEntity.scala
- core/src/com/bot4s/telegram/models/MessageEntityType.scala
- core/src/com/bot4s/telegram/models/Sticker.scala
- core/src/com/bot4s/telegram/models/StickerSet.scala
- core/src/com/bot4s/telegram/models/StickerType.scala
- core/test/src/com/bot4s/telegram/marshalling/MarshallingSuite.scala
> [api] Support v6.2

- core/src/com/bot4s/telegram/marshalling/CirceDecoders.scala
- core/src/com/bot4s/telegram/methods/RestrictChatMember.scala
- core/src/com/bot4s/telegram/methods/SetChatPermissions.scala
- core/src/com/bot4s/telegram/models/ChatJoinRequest.scala
- core/src/com/bot4s/telegram/models/ChatMember.scala
- core/src/com/bot4s/telegram/models/ChatPermissions.scala
- core/src/com/bot4s/telegram/models/ChatShared.scala
- core/src/com/bot4s/telegram/models/Message.scala
- core/src/com/bot4s/telegram/models/ReplyMarkup.scala
- core/src/com/bot4s/telegram/models/UserShared.scala
https://core.telegram.org/bots/api#february-3-2023
> [api] Support v6.5

- README.md
- build.sc
- core/src/com/bot4s/telegram/marshalling/CirceDecoders.scala
- core/src/com/bot4s/telegram/marshalling/CirceEncoders.scala
- core/src/com/bot4s/telegram/methods/PromoteChatMember.scala
- core/src/com/bot4s/telegram/methods/UnpinAllGeneralForumTopicMessages.scala
- core/src/com/bot4s/telegram/models/Chat.scala
- core/src/com/bot4s/telegram/models/ChatMember.scala
- core/src/com/bot4s/telegram/models/Message.scala
- core/src/com/bot4s/telegram/models/Story.scala
- core/src/com/bot4s/telegram/models/WriteAccessAllowed.scala
Bot API 6.9
Bot API 6.8
Notes: polls are missing from this bot, I will add them in the future, they were added a long time ago in 4.6 https://core.telegram.org/bots/api-changelog#january-23-2020
> Support API 6.8 and 6.9

- core/src/com/bot4s/telegram/api/RequestHandler.scala
This PR provide a change of sendRequestInternal method from private to protected for opportunity to override apply method without copying of sendRequestInternal method.
> change sendRequestInternal from private to protected

- build.sc
For now, `core` depends on logback. It's pretty uncommon for a library to depend on a concrete slf4j implementation (usually, it's up to the end application to decide which implementation to use).
This PR removes redundant logback dependency from the `core` and adds it to `examples`.
P.S. I'm new to Mill, so that may be not an idiomatic way to solve the issue :sweat_smile:
> fix(core): Get rid of redundant logback dependency

- core/src/com/bot4s/telegram/models/ReplyMarkup.scala
Exactly one of the optional fields must be used to specify type of the button. https://core.telegram.org/bots/api#inlinekeyboardbutton
> Fix inline webapp button
